name: Run py unit tests
on: [pull_request]
jobs:
  py_lint_and_unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all] --upgrade
    - name: Test with py-unittest
      run: |
        coverage run -a -m unittest
        coverage report -m --omit="*/test*" --fail-under=75
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --max-complexity=25 --max-line-length=79 --statistics --benchmark --ignore=H104,W503
